change1-1---

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,40 +1,38 @@
 #!/bin/sh
 
-# Get list of staged files
-FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
+# Fetch only modified staged files that match the specified types
+# STAGED_FILES=$(git diff --cached --name-only --diff-filter=M | grep "\.jsx\?$\|\.tsx\?$\|\.js$\|\.ts$")
+# [ -z "$STAGED_FILES" ] && exit 0
 
-# Check if there are any staged files
-[ -z "$FILES" ] && exit 0
+# # Prettify all selected files
+# echo "$STAGED_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
 
-# Prettify all selected files
-echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
+# echo -e "\nValidating Javascript & Typescript with ESLint:"
+# echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix
 
-echo -e "\nValidating JavaScript and TypeScript with ESLint and TypeScript Compiler:"
+# echo -e "ESLint validation completed."
 
-# Separate JavaScript and TypeScript files
-STAGED_JS_FILES=$(echo "$FILES" | grep ".jsx\{0,1\}$\|\.js$")
-STAGED_TS_FILES=$(echo "$FILES" | grep "\.tsx\{0,1\}$\|\.ts$")
+# # Generate a temporary tsconfig file for staged files
+# TMP_TSCONFIG=$(mktemp)
+# cat <<EOF > $TMP_TSCONFIG
+# {
+#   "include": [
+#     $(echo "$STAGED_FILES" | sed 's|^|    "|;s|$|",|' | tr '\n' ' ')
+#   ]
+# }
+# EOF
 
-# Run ESLint for JavaScript files
-if [ -n "$STAGED_JS_FILES" ]; then
-  echo "$STAGED_JS_FILES" | xargs ./node_modules/.bin/eslint --fix
-fi
+# # Compile only staged TypeScript files to check for errors
+# echo -e "\nCompiling Javascript & Typescript files to check for errors:"
+# ./node_modules/.bin/tsc --noEmit --skipLibCheck -p $TMP_TSCONFIG
+# tsc_result=$?
+# rm $TMP_TSCONFIG
+# if [ $tsc_result -ne 0 ]; then
+#   echo "Javascript & Typescript compilation errors found. Aborting commit."
+#   exit 1
+# fi
 
-# Run TypeScript Compiler for TypeScript files
-if [ -n "$STAGED_TS_FILES" ]; then
-  for file in $STAGED_TS_FILES; do
-    tsc_output=$(./node_modules/.bin/tsc --noEmit $file)
-    tsc_exit_code=$?
+# # Add back the modified/prettified files to staging
+# echo "$STAGED_FILES" | xargs git add
 
-    if [ $tsc_exit_code -ne 0 ]; then
-      echo "TypeScript compilation failed for $file. Please fix the errors."
-    fi
-  done
-fi
-
-echo -e "JavaScript and TypeScript validation completed."
-
-# Add back the modified/prettified files to staging
-echo "$FILES" | xargs git add
-
-exit $?
+# exit 0
