change--5--

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,43 +1,38 @@
 #!/bin/sh
 
-FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
-[ -z "$FILES" ] && exit 0
+# Fetch only modified staged files that match the specified types
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR HEAD | grep "\.jsx\?$\\|\\.tsx\?$\\|\\.js$\\|\\.ts$")
+[ -z "$STAGED_FILES" ] && exit 0
 
-echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
+# Prettify all selected files
+echo "$STAGED_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
 
-echo -e "\nValidating Javascript & Typescript with eslint:"
+echo -e "\nValidating Javascript & Typescript with ESLint:"
+echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix
 
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.jsx?$|\.tsx?$|\.js$|\.ts$")
+echo -e "ESLint validation completed."
 
-if [ -n "$STAGED_FILES" ]; then
-  ESLINT_OUTPUT=$(echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix --format json)
+# Generate a temporary tsconfig file for staged files
+TMP_TSCONFIG=$(mktemp)
+cat <<EOF > $TMP_TSCONFIG
+{
+  "include": [
+$(echo "$STAGED_FILES" | sed 's|^|    "|;s|$|",|' | tr '\n' '\n')
+  ]
+}
+EOF
 
-  if echo "$ESLINT_OUTPUT" | grep -q '"errorCount": [1-9]'; then
-    echo -e "ESLint found errors, aborting commit."
-    echo "$ESLINT_OUTPUT" | ./node_modules/.bin/eslint-formatter-friendly
-    exit 1
-  else
-    echo -e "ESLint validation completed successfully."
-  fi
+# Compile only staged TypeScript files to check for errors
+echo -e "\nCompiling Javascript & Typescript files to check for errors:"
+./node_modules/.bin/tsc --noEmit --skipLibCheck -p $TMP_TSCONFIG
+tsc_result=$?
+rm $TMP_TSCONFIG
+if [ $tsc_result -ne 0 ]; then
+  echo "Javascript & Typescript compilation errors found. Aborting commit."
+  exit 1
 fi
 
-echo -e "\nValidating JavaScript & TypeScript compilation:"
-TS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E  "\.tsx?$|\.ts$|\.jsx?$|\.js$")
-
-if [ -n "$TS_FILES" ]; then
-  for FILE in $TS_FILES
-  do
-    ./node_modules/.bin/tsc --noEmit "$FILE"
-    if [ $? -ne 0 ]; then
-      echo -e " JavaScript & TypeScript compilation failed for $FILE, aborting commit."
-      exit 1
-    fi
-  done
-fi
-
-
-
-echo "$FILES" | xargs git add
+# Add back the modified/prettified files to staging
 echo "$STAGED_FILES" | xargs git add
 
 exit 0
