change1-1----

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,38 +1,38 @@
 #!/bin/sh
 
 # Fetch only modified staged files that match the specified types
-# STAGED_FILES=$(git diff --cached --name-only --diff-filter=M | grep "\.jsx\?$\|\.tsx\?$\|\.js$\|\.ts$")
-# [ -z "$STAGED_FILES" ] && exit 0
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=M | grep "\.jsx\?$\|\.tsx\?$\|\.js$\|\.ts$")
+[ -z "$STAGED_FILES" ] && exit 0
 
-# # Prettify all selected files
-# echo "$STAGED_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
+# Prettify all selected files
+echo "$STAGED_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
 
-# echo -e "\nValidating Javascript & Typescript with ESLint:"
-# echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix
+echo -e "\nValidating Javascript & Typescript with ESLint:"
+echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix
 
-# echo -e "ESLint validation completed."
+echo -e "ESLint validation completed."
 
-# # Generate a temporary tsconfig file for staged files
-# TMP_TSCONFIG=$(mktemp)
-# cat <<EOF > $TMP_TSCONFIG
-# {
-#   "include": [
-#     $(echo "$STAGED_FILES" | sed 's|^|    "|;s|$|",|' | tr '\n' ' ')
-#   ]
-# }
-# EOF
+# Generate a temporary tsconfig file for staged files
+TMP_TSCONFIG=$(mktemp)
+cat <<EOF > $TMP_TSCONFIG
+{
+  "include": [
+    $(echo "$STAGED_FILES" | sed 's|^|    "|;s|$|",|' | tr '\n' ' ')
+  ]
+}
+EOF
 
-# # Compile only staged TypeScript files to check for errors
-# echo -e "\nCompiling Javascript & Typescript files to check for errors:"
-# ./node_modules/.bin/tsc --noEmit --skipLibCheck -p $TMP_TSCONFIG
-# tsc_result=$?
-# rm $TMP_TSCONFIG
-# if [ $tsc_result -ne 0 ]; then
-#   echo "Javascript & Typescript compilation errors found. Aborting commit."
-#   exit 1
-# fi
+# Compile only staged TypeScript files to check for errors
+echo -e "\nCompiling Javascript & Typescript files to check for errors:"
+./node_modules/.bin/tsc --noEmit --skipLibCheck -p $TMP_TSCONFIG
+tsc_result=$?
+rm $TMP_TSCONFIG
+if [ $tsc_result -ne 0 ]; then
+  echo "Javascript & Typescript compilation errors found. Aborting commit."
+  exit 1
+fi
 
-# # Add back the modified/prettified files to staging
-# echo "$STAGED_FILES" | xargs git add
+# Add back the modified/prettified files to staging
+echo "$STAGED_FILES" | xargs git add
 
-# exit 0
+exit 0
