change1-44-

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,38 +1,27 @@
 #!/bin/sh
 
-# Fetch only modified staged files that match the specified types
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=M | grep "\.jsx\?$\|\.tsx\?$\|\.js$\|\.ts$")
-[ -z "$STAGED_FILES" ] && exit 0
+# Define regular expression for file types
+# FILE_TYPES="\.jsx?$|\.tsx?$|\.js$|\.ts$"
 
-# Prettify all selected files
-echo "$STAGED_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
+# failWithMessage() {
+#     echo >&2 "$1"
+#     exit 1
+# }
 
-echo -e "\nValidating Javascript & Typescript with ESLint:"
-echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix
+# # Check for staged files that match file types
+# staged_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E $FILE_TYPES)
+# [ -z "$staged_files" ] && exit 0
 
-echo -e "ESLint validation completed."
+# # Check if any staged files have compile errors
+# for file in $staged_files; do
+#     if [[ $file =~ \.jsx?$|\.tsx?$ ]]; then
+#         # For JSX and TSX files, use babel-eslint for parsing
+#         eslint --ext .jsx,.js,.tsx,.ts --parser babel-eslint "$file" || failWithMessage "ESLint found errors in $file. Please fix them before committing."
+#     else
+#         # For JS and TS files, use regular parser
+#         eslint --ext .js,.ts "$file" || failWithMessage "ESLint found errors in $file. Please fix them before committing."
+#     fi
+# done
 
-# Generate a temporary tsconfig file for staged files
-TMP_TSCONFIG=$(mktemp)
-cat <<EOF > $TMP_TSCONFIG
-{
-  "include": [
-    $(echo "$STAGED_FILES" | sed 's|^|    "|;s|$|",|' | tr '\n' ' ')
-  ]
-}
-EOF
-
-# Compile only staged TypeScript files to check for errors
-echo -e "\nCompiling Javascript & Typescript files to check for errors:"
-./node_modules/.bin/tsc --noEmit --skipLibCheck -p $TMP_TSCONFIG
-tsc_result=$?
-rm $TMP_TSCONFIG
-if [ $tsc_result -ne 0 ]; then
-  echo "Javascript & Typescript compilation errors found. Aborting commit."
-  exit 1
-fi
-
-# Add back the modified/prettified files to staging
-echo "$STAGED_FILES" | xargs git add
-
-exit 0
+# # If all checks pass, allow the commit
+# exit 0
